# Generated by Django 5.1 on 2024-08-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="attendance_photos/"
            ),
        ),
    ]
